"""fix google_token_expiry type

Revision ID: 0faaa2cdc525
Revises: 163c83dfb807
Create Date: 2026-05-30 14:51:53.449262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faaa2cdc525'
down_revision: Union[str, Sequence[str], None] = '163c83dfb807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activities_source'), 'activities', ['source'], unique=False)
    op.alter_column(
        'tokens',
        'google_token_expiry',
        type_=sa.DateTime(),
        postgresql_using='google_token_expiry::timestamp without time zone'
    )
    op.drop_constraint(op.f('users_google_account_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_token_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_token_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_google_account_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_google_account_id_fkey'), 'users', 'google_accounts', ['google_account_id'], ['id'])
    op.create_foreign_key(op.f('users_token_id_fkey'), 'users', 'tokens', ['token_id'], ['id'])
    op.create_unique_constraint(op.f('users_token_id_key'), 'users', ['token_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_google_account_id_key'), 'users', ['google_account_id'], postgresql_nulls_not_distinct=False)
    op.alter_column(
        'tokens',
        'google_token_expiry',
        type_=sa.Integer(),
        postgresql_using='extract(epoch from google_token_expiry)::integer'
    )
    op.drop_index(op.f('ix_activities_source'), table_name='activities')
    # ### end Alembic commands ###
