"""initial migrations 2

Revision ID: 16cbe45cbb18
Revises: 6409c4bbf1a2
Create Date: 2026-01-24 23:01:47.862662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cbe45cbb18'
down_revision: Union[str, Sequence[str], None] = '6409c4bbf1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_accounts', sa.Column('token_id', sa.Integer(), nullable=True))
    op.add_column('google_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'google_accounts', ['token_id'])
    op.create_foreign_key(None, 'google_accounts', 'tokens', ['token_id'], ['id'])
    op.create_foreign_key(None, 'google_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_accounts', type_='foreignkey')
    op.drop_constraint(None, 'google_accounts', type_='foreignkey')
    op.drop_constraint(None, 'google_accounts', type_='unique')
    op.drop_column('google_accounts', 'user_id')
    op.drop_column('google_accounts', 'token_id')
    # ### end Alembic commands ###
