"""initial migration

Revision ID: 6409c4bbf1a2
Revises: 
Create Date: 2026-01-24 22:48:39.571903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6409c4bbf1a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('google_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['google_account_id'], ['google_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('user_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_hour', sa.DateTime(), nullable=True),
    sa.Column('ending_hour', sa.DateTime(), nullable=True),
    sa.Column('available_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_availability_available_days'), 'user_availability', ['available_days'], unique=False)
    op.create_index('ix_user_availability_available_days_category', 'user_availability', [sa.literal_column("(available_days ->> 'category')")], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_user_availability_ending_hour'), 'user_availability', ['ending_hour'], unique=False)
    op.create_index(op.f('ix_user_availability_id'), 'user_availability', ['id'], unique=False)
    op.create_index(op.f('ix_user_availability_starting_hour'), 'user_availability', ['starting_hour'], unique=False)
    op.create_index(op.f('ix_google_accounts_email'), 'google_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_google_accounts_google_sub'), 'google_accounts', ['google_sub'], unique=True)
    op.drop_column('google_accounts', 'access_token')
    op.drop_column('google_accounts', 'token_expiry')
    op.drop_column('google_accounts', 'refresh_token')
    op.create_foreign_key(None, 'user_info', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['token_id'])
    op.create_foreign_key(None, 'users', 'tokens', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token_id')
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.add_column('google_accounts', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('google_accounts', sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('google_accounts', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_google_accounts_google_sub'), table_name='google_accounts')
    op.drop_index(op.f('ix_google_accounts_email'), table_name='google_accounts')
    op.drop_index(op.f('ix_user_availability_starting_hour'), table_name='user_availability')
    op.drop_index(op.f('ix_user_availability_id'), table_name='user_availability')
    op.drop_index(op.f('ix_user_availability_ending_hour'), table_name='user_availability')
    op.drop_index('ix_user_availability_available_days_category', table_name='user_availability', postgresql_using='btree')
    op.drop_index(op.f('ix_user_availability_available_days'), table_name='user_availability')
    op.drop_table('user_availability')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
